development:
  password: c47784ff7c20ff15e618cc07f43d9bde
  theme_id: "41463152728"
  store: liberte-dev.myshopify.com
ignores_files:
  - .git
  - .DS_Store
  - config.yml
  - README.md
  - config/settings_data.json
